# -*- coding: utf-8 -*-
"""Programming_Assignment02_DTS2455.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13thUIRbZE-8H69ETK_z5UKsJgFtlY_3C
"""

!pip install ultralytics opencv-python torch torchvision -q

import cv2
import os
import glob
import torch
from ultralytics import YOLO
print("CUDA available:", torch.cuda.is_available())

from google.colab import drive
drive.mount('/content/drive')

video_folder = "/content/drive/MyDrive/videos_dataset"
video_files = glob.glob(video_folder + "/*.mp4")

print("Found videos:")
for v in video_files:
    print(v)

# Player detection + tracking model
model = YOLO("yolov8n.pt")

# Pose estimation model (keypoints)
pose_model = YOLO("yolov8n-pose.pt")

output_folder = "/content/drive/MyDrive/videos_output"
os.makedirs(output_folder, exist_ok=True)

print("Output folder:", output_folder)

for i, video_path in enumerate(video_files, start=1):
    print(f"\nProcessing TRACKING video {i}: {video_path}")

    cap = cv2.VideoCapture(video_path)

    # Get video properties (IMPORTANT FIX)
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    output_path = os.path.join(output_folder, f"tracked_video_{i}.mp4")

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # =========================
        # YOLOv8 TRACKING (KEY FIX)
        # =========================
        results = model.track(
          frame,
          persist=True,
          classes=[0],
          tracker="bytetrack.yaml",
          verbose=False
)

        annotated_frame = results[0].plot()
        out.write(annotated_frame)

    cap.release()
    out.release()

    print(f"✅ Tracking saved: {output_path}")

for i, video_path in enumerate(video_files, start=1):
    print(f"\nProcessing POSE video {i}: {video_path}")

    cap = cv2.VideoCapture(video_path)

    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    output_path = os.path.join(output_folder, f"pose_video_{i}.mp4")

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Pose estimation
        results = pose_model(frame)

        annotated_frame = results[0].plot()
        out.write(annotated_frame)

    cap.release()
    out.release()

    print(f"🎯 Pose saved: {output_path}")

print("\n✅ ALL PROCESSING COMPLETE")
print("Output folder:", output_folder)

!ls -lh "$output_folder"